# Quartermaster Roll Call workflow
# - Triggers: run on push to main and manual dispatch so the crew can call it anytime.
# - Job: uses Ubuntu with Python 3.11 to match the ship's simple needs.
# - Steps: checkout code, optionally install tools, then run the roll call script from its folder.
name: Quartermaster Roll Call

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-quartermaster:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download previous wagon database
        uses: actions/download-artifact@v4
        with:
          name: wagon-database
          path: quartermaster
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Database setup
        run: |
          echo "::group::Database setup"
          python inventory_setup.py
          echo "::endgroup::"
        working-directory: quartermaster

      - name: Quartermaster operations
        run: |
          echo "::group::Quartermaster operations"
          python quartermaster.py
          echo "::endgroup::"
        working-directory: quartermaster

      - name: Ledger review
        run: |
          echo "::group::Ledger review"
          python ledger_review.py
          echo "::endgroup::"
        working-directory: quartermaster

      - name: Upload wagon database
        uses: actions/upload-artifact@v4
        with:
          name: wagon-database
          path: quartermaster/wagon.db
